sudo: false

# NOTE: dist is added here to ensure that Travis CI works consistently
# on Node.js 12. It is desired to remove it once this issue is resolved
# or otherwise goes away.
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - TERM=dumb # Keep gradle from crapping all over the log
  matrix:
    - nodejs_version=6
    - nodejs_version=8
    - nodejs_version=10
    - nodejs_version=12

language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - nvm install $nodejs_version
  - node --version
  - npm --version
  - gradle --version

install:
  - npm install

before_script:
  - npm install -g cordova
  - cordova platform add browser
  - cordova platform add android

script:
  - cordova build browser
  - cordova build android

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: platforms/browser/www