language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - npm install -g cordova
  - cordova platform add browser

script:
  - cordova build browser

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: platforms/browser/www